# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
# Copyright 2025 Canonical Ltd.
name: GitHub release and Docker images

on:
  push:
    tags:
      - v*

jobs:
  tag-github:
    uses: omec-project/.github/.github/workflows/tag-github.yml@main

  release-image:
    needs: tag-github
    uses: omec-project/.github/.github/workflows/release-image.yml@main
    with:
      branch_name: ${{ github.ref }}
    secrets: inherit

  update-version:
    needs: tag-github
    uses: omec-project/.github/.github/workflows/update-version.yml@main
    secrets: inherit

  branch-release:
    needs: tag-github
    uses: omec-project/.github/.github/workflows/update-version.yml@main
    secrets: inherit

